---
# handlers file for hosting
- name: firewall
  service:
    name: firewalld
    state: reloaded
- name: restart httpd
  service:
    name: "{{packalma}}"
    state: restarted
- name: ufw
  service:
    name: ufw
    state: reloaded
- name: restart apache2
  service:
    name: "{{packub}}"
    state: restarted
